### ISSUE TITLE
GeCoS_IO I2C warnings

### ISSUE THREAD

**Issue by ETM2000** [Joey-1970/GeCoS-Modules#4]
Hello Joachim,
thanks for the GeCoS modules. I use the GeCoS_IO_V2 with IP-Symcon (pigpio_V68). I get between 50 and 100 warnings a day, e.g.:

01/22/2022, 07:50:02 | GeCoS_IO I2C Read Bytes on Handle | Handle: 3 Error message: PI_I2C_READ_FAILED
01/22/2022, 07:50:02 | GeCoS_IO I2C Write Byte on Handle | Handle: 3 Register: 80 Error message: PI_I2C_WRITE_FAILED
01/22/2022, 07:50:05 | GeCoS_IO I2C Read Bytes on Handle | Handle: 3 Error message: PI_I2C_READ_FAILED
01/22/2022, 08:43:14 | GeCoS_IO I2C Read Block Bytes | Handle: 8 Registers: 18 Error message: PI_I2C_READ_FAILED

I was hoping to ignore the warnings, but I've found that outputs sometimes don't switch. I've helped myself so far by repeating actions, but I'd like to fix somewhere else.

How can I interpret/evaluate the handle and register numbers from the warnings?
Thank you.

Greetings
Peer

**Comment by Thomas-GeDaD** [comment]
Hi Peer,
what Server Version do you use? (The Hardware)
Have you installed the newest Version of the Read/Write script?
https://github.com/bgersmann/GeCoS-Server
I use 5 GeCoS Server in my home and many more at my customer without any Errors or Wanings..

**Comment by ETM2000** [comment]
Hello Thomas,
Thanks for the fast answer.
Is it necessary to install the server (https://github.com/bgersmann/GeCoS-Server) if I want to access the GeCoS_IO modules with IP-Symcon PHP?
I thought Joachim's Symcon modules (https://github.com/Joey-1970/GeCoS-Modules) allow me to access the GeCoS_IO modules. 
![GeCoS_IO_V2](https://user-images.githubusercontent.com/98207565/150638008-423c9589-b01e-43ec-bd7d-610c5a7ea521.png)
Hardware Version I²C 16 Out: V2.1

**Comment by Thomas-GeDaD** [comment]
Yes, the normal way is, that on the Pi wich is on the "Server Hardware" you install the https://github.com/bgersmann/GeCoS-Server .On the  modul where Symcon is located, you install https://github.com/Joey-1970/GeCoS-Modules  #(GeCoS_IO_V2)  .(It could be the same Pi).  So you can use one Pi with Symcon and many Pi´s with the Server Script without Symcon and you can controll them with several GeCoS_IO_V2 Instanzes. With the old GeCoS_IO it was another method. The old GeCoS_IO works with pigpio, the new with TCP and the GeCoS-Server. The Performance is much higher and you didn´t loose any switching operations when someone "click" with a high frequency on a switch. ;-) but be careful, the V2 only works with the newer V2 Hardware Server. not with the V1.x. If you have an older "Server board" you have to use the GeCoS_IO not the V2.

**Comment by ETM2000** [comment]
Hello Thomas,
I followed the instructions from " https://github.com/bgersmann/GeCoS-Server" for the installation. Can I uninstall pigpio? I only use hardware version 2 from the GeCoS server.
The status display is initially empty. I keep watching here. Thank you very much for your competent help.

In Joachim's GeCoS_IO_V2-Modul.php an error was noted in line 2781. I changed "$data [0]" to "$data" in line 2781 of module.php. Now I can also evaluate 1-wire DS18B20 temperatures. That wasn't possible before. Am I right?

Many greetings
peer

**Comment by Thomas-GeDaD** [comment]
I havent any issues with the 1-Wire. We use many 1-Wire devices.  But i think there Joachim can take a look?

**Comment by Thomas-GeDaD** [comment]
Also not sure with pigpio.  @Joey-1970 ? @bgersmann ?

**Comment by ETM2000** [comment]
After the change described above, I have fewer warnings than before. But the I²C warnings are still there.
![Status](https://user-images.githubusercontent.com/98207565/150687843-b9390f61-185a-4e3b-a965-9518de201f35.png)
![Statusprotokoll](https://user-images.githubusercontent.com/98207565/150687852-a08d0168-d78a-440c-8b2d-616a43181421.png)

**Comment by Joey-1970** [comment]
Hello all!

Sorry for delay! I don't think that is a problem of this module, I think this is a problem of IP-Symcon 6.0. I have the same here so I switch to the "Server-Version" like Thomas write. 
There is no need to uninstall pigpio.

Joachim

**Comment by Joey-1970** [comment]
...have you switch in IP-Modules from "master" to "server"?

Joachim

**Comment by ETM2000** [comment]
My GeCoS module branch is set to "master".
I'll try "server" now.
Thanks for the feedback.

**Comment by ETM2000** [comment]
Hello all,
i tried the server branch. But "I/O Instanz/ Client socket" and "Splitter Instanz/ GeCoS_IO_V2" doesn't work with network port 8000. I went back to "master ".

I found "GeCoS_Configurator"- and "GeCoS_OWConfigurator"-Module in "Server-branch". What are these for?
What do I have to do to get the server branch up and running?

Past success : My warnings slow down to 30 a day.

Thank you for your support. 

Peer

**Comment by Joey-1970** [comment]
Hello Peer,

you first have to install the server on the raspberry pi where the GeCoS-Server (hardware) ist connected. (Instruction here: https://github.com/bgersmann/GeCoS-Server)
In IP-Symcon you must change the module to "server", open the Splitter and maybe use "Restart Server Software", in the modules you must change the bus. "GeCoS_Configurator"- and "GeCoS_OWConfigurator" can help you to find the hardware, but it will make new instances...

Joachim

**Comment by ETM2000** [comment]
Hello all,
I'm too stupid to start the server (https://github.com/bgersmann/GeCoS-Server). I went through the instructions, adjusted the config.txt and also restarted Raspberry. 
 @bgersmann: can you help?  
Peer
![gecos service_failed](https://user-images.githubusercontent.com/98207565/151558949-de6a9d55-b1b8-442b-b236-4af128426d13.png)

**Comment by bgersmann** [comment]
Hi,
I made a small change to the Script, please update it and try again. 

sudo wget -O /usr/local/bin/GeCoS-Server.py https://raw.githubusercontent.com/bgersmann/GeCoS-Server/master/GeCoS-Server.py

sudo systemctl restart gecos.service

That sould be enough to update...

**Comment by ETM2000** [comment]
Great. The server is running. Thanks so much. 
I will now test Joachim's server branch.

**Comment by ETM2000** [comment]
Hi Joachim,
can you please check warning in the **master** branch: 
![DS18B20_in_GeCoS_IO_V2](https://user-images.githubusercontent.com/98207565/151605876-19ab711f-8ed2-46ca-beed-ca7c4f09bbfb.png)
I think "$Data[0]" should just be "$Data" in line 2781. ( /var/lib/symcon/modules/GeCoS-Modules/GeCoS_IO_V2/module.php)


I will **now** test your **server branch**. Top work from you. 

Thanks again everyone.

**Comment by ETM2000** [comment]
Hi there,
me again. Server is running.

Now I have another problem with the **server** branch:
The "GeCoS-4AnalogIn"-Module measured values are not correct.
Example: 
Ch1: 4.000V
Ch2: 5,000V
Ch3: 3,000V
Ch4: 4,000V
The decimal places are cut off. Could this be an "cast integer float thing"?
Thank you for your patience.

**Comment by Joey-1970** [comment]
Hello Peer,

I don't think that "$Data" is the right way. For all other users it work with "$Data[0]" for the array that are needed. In the case there is no array it doesn't work. I should check it before this line and exit the code if this is not a array.

bgersmann and I must look what is happend in the 4AnalogIn-Module, maybe your a right...

Joachim

**Comment by Joey-1970** [comment]
Hello Peer,

maybe I find the reason for the wrong Values of the 4AnaloIn-Module - but I can't test it here. Please try a update of the IP-Symcon module...

Joachim

**Comment by ETM2000** [comment]
Good evening Joachim,
I tested your updated "server branch". The GeCoS-4AnalogIn device is working fine now.
Thank you for your help. I will monitor my status reports for next 24 hours and then close the issue.

If you need a tester, I have the GeCoS server, GeCoS-4AnlogIn, GeCoS-16Out and GeCoS-16In.

Many thanks to everyone who helped to solve my problem.

Best regards
Peer

**Comment by ETM2000** [comment]
Good evening Joachim,
no longer I get any warnings.

Where I still have a problem is with 1-wire. I created two DS18B20 instances with the GeCoS-OWireConfigurator. Unfortunately, the displayed temperature is more than 3 times too high. Do you have a tip for me?
Thank you. Greetings Peer

**Comment by ETM2000** [comment]
here is my Gateway Debug for two DS18B20 sensors:
![Debug_Gateway](https://user-images.githubusercontent.com/98207565/152004600-3ab7b92f-70f2-4ee4-89ab-febbcae6e3c6.png)
 @bgersmann can you also please take a look of DS18B20 implementation in your server.
thx Peer

**Comment by bgersmann** [comment]
Hi, I have 7 DS18B20 running here without problems. Did you try to change the resolution in configuration if it changes something?

**Comment by ETM2000** [comment]
Yes I tried different resolutions.  What I noticed: the decimal place is always zero.

**Comment by Joey-1970** [comment]
Hello Peer,

are you sure that also DS18B20 have enough power?

Joachim

**Comment by ETM2000** [comment]
Hi,
I disconnected the DS18B20 from the GeCoS server and reconnected it. Now the correct values are displayed.

I would like to take this opportunity to thank you all once again for the good support.
Peer
